1 - Introduction/1 - Solve me first/huy.scala

Added solve me first solution in Scala for #1

Added solve me first solution in Scala

---

1 - Introduction/1 - Solve me first/palutz.fs
1 - Introduction/2 - Hello World/palutz.fs
1 - Introduction/3 - Hello World N Times/palutz.fs

F# functional solutions to Intro problems (1 to 3)

---

1 - Introduction/4 - List Replication/palutz.fs
1 - Introduction/5 - Filter Array/palutz.fs
1 - Introduction/7 - Array Of N Elements/palutz.fs

f# solutions to intro problems (4 and 5)

---

1 - Introduction/1 - Solve me first/machad0.erl
1 - Introduction/2 - Hello World/machad0.erl
1 - Introduction/3 - Hello World N Times/machad0.erl

feat: erlang solution to solve me first
feat: erlang solution to hello world
feat: erlang solution to hello world n times

feat: erlang solutions to problems 1-3

---

1 - Introduction/4 - List Replication/petmat.fs

This is my F# solution to the List Replication problem.

Add F# solution to List Replication problem

---

1 - Introduction/1 - Solve me first/petmat.fs
1 - Introduction/2 - Hello World/petmat.fs

These are two first solutions to these problems using F#.
Thank you for this awesome repo!
This is a great way to learn functional programming.

Add F# solutions to Solve Me First FP and Hello World problems

---

1 - Introduction/8 - Reverse a List/huyvo.scala

Solve [Reverse a list](https://www.hackerrank.com/challenges/fp-reverse-a-list/problem) using Scala.

Add reverse list solution in Scala

---

1 - Introduction/10 - List Length/huyvo.scala

Solve [List length](https://www.hackerrank.com/challenges/fp-list-length/problem) using Scala.

Add list length solution in Scala

---

1 - Introduction/7 - Array Of N Elements/huyvo.scala

Solve [array of n elements](https://www.hackerrank.com/challenges/fp-array-of-n-elements/problem) using Scala.

Add array of n elements solution in Scala

---

1 - Introduction/7 - Array Of N Elements/c-kaieong.ex

Solution for introductory [array of n elements](https://www.hackerrank.com/challenges/fp-array-of-n-elements/problem) problem in elixir

Implement Array of N in Elixir

---

6 - Ad Hoc/3 - Remove Duplicates/c-kaieong.ex

Solved [remove duplicates](https://www.hackerrank.com/challenges/remove-duplicates/problem) in Elixir

Elixir implementation of remove duplicates

---

2 - Recursion/2 - Fibonacci Numbers/c-kaieong.ex

Implemented the Fibonacci Sequence problem in Elixir. Supply n, where n is the number of iterations.

Elixir implementation of Fibonacci Numbers

---

1 - Introduction/1 - Solve me first/silvaemerson.clj
1 - Introduction/3 - Hello World N Times/silvaemerson.clj
1 - Introduction/6 - Filter Positions in a List/silvaemerson.clj
1 - Introduction/7 - Array Of N Elements/silvaemerson.clj

I implemented Clojure solutions for the following problems:
* Solve me First
* Hello World N Times
* Filter Positions in a List
* Array Of N Elements

Add Clojure solutions of some introduction problems

---

1 - Introduction/1 - Solve me first/tom-vthptvh.rkt

Add Racket solution to Solve Me First

#35 Add Racket solution to Solve Me First

---

1 - Introduction/2 - Hello World/tom-vthptvh.rkt

Add Racket solution of [Hello World](https://www.hackerrank.com/challenges/fp-hello-world/problem)
Ticket #35

Add Racket solution to Hello World

---

1 - Introduction/3 - Hello World N Times/tom-vthptvh.rkt

Add Racket solution of [Hello World N Times](https://www.hackerrank.com/challenges/fp-hello-world-n-times/problem)
Issue #35

Add Racket solution to Hello World N Times

---

1 - Introduction/4 - List Replication/tom-vthptvh.rkt

Add Racket solution of [List Replication](https://www.hackerrank.com/challenges/fp-list-replication/problem)
Issue #35

Add Racket solution to List Replication

---

1 - Introduction/10 - List Length/tom-vthptvh.rkt

Add Racket solution of [List Length](https://www.hackerrank.com/challenges/fp-list-length/problem)
Issue #35

Add Racket solution to List Length

---

1 - Introduction/README.md

Added links for all problems on Introduction README.

Add links to Introduction problems on README 

---

1 - Introduction/1 - Solve me first/leandrotk.clj
1 - Introduction/2 - Hello World/leandrotk.clj
1 - Introduction/3 - Hello World N Times/leandrotk.clj
1 - Introduction/4 - List Replication/leandrotk.clj
1 - Introduction/5 - Filter Array/leandrotk.clj
1 - Introduction/7 - Array Of N Elements/leandrotk.clj

Solved:
- Solve me First
- Hello World
- Hello World N Times
- List Replication
- Filter Array
- Array Of N Elements

Add some solutions to introduction problems

---

1 - Introduction/24 - Compute the Perimeter of a Polygon/jereinhardt.ex

Add elixir solution to Compute the Perimeter of a Polygon

---

1 - Introduction/11 - Update List/huyvo.scala

Update list solution in Scala

---

1 - Introduction/5 - Filter Array/huyvo.scala

Add filter array solution in Scala

Filter array in Scala

---

1 - Introduction/9 - Sum of Odd Elements/sum_of_odd_elements.scala

Add sum of odd elements solution in Scala

Add sum of odd elements solution in Scala

---

1 - Introduction/24 - Compute the Perimeter of a Polygon/viniciusfk9.hs

Add haskell solution to Compute the Perimeter of a Polygon
